#ifndef __DEPLOYER_H
#define __DEPLOYER_H

#include <stdint.h> // uint8_t

int deployer_is_active(void);

// Code in out/canboot_payload.c generated by scripts/buildbinary.py
extern const uint8_t deployer_canboot_binary[];
extern const uint32_t deployer_canboot_binary_size;

#endif // deployer.h
