name: Test Katapult Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
          libnewlib-arm-none-eabi \
          gcc-arm-none-eabi \
          binutils-arm-none-eabi

    - name: Run Tests
      run: ./scripts/test-build.sh 2>&1
